### PR TITLE
Elasticsearch basic authentication - user and password fixed. 

### PR DESCRIPTION
**Pull request by orinciog**
Resolved https://github.com/royrusso/elasticsearch-HQ/issues/246

Added Grunt target for serving index.html from server.

### CODE REVIEW

**Comment by mjalil** [comment]
I tested using `http://username:pass@example.com:9200` and that was OK

**Comment by mjalil** [comment]
I failed to create an alias from the "create alias" page. the error is : `unknown field [connectionRootURL]`. 
the request payload is : 
`{"connectionRootURL":"http://elastic:changeme@localhost:9200","indexId":"test_0","aliasId":"test","index_routing":"","search_routing":"","actions":[{"add":{"index":"test_0","alias":"test"}}]}`

while sending `post` request to `http://localhost:9200/_aliases`

**Comment by orinciog** [comment]
@mjalil Hello! Thank you for your comment! Which elasticsearch version are you using? elasticsearch-HQ doesn't fully support ES5.x. One of the features that are not supported is alias creation (Request made to elasticsearch is no more supported for 5.x version).

**Comment by mjalil** [comment]
@orinciog you are right. I posted a request using PostMan and ES-Head but then ES 5.5.1 responds `403 Forbidden`. I don't remember how I created a `test1` alias, maybe with Kibana or cerebro. both of them use a proxy instead of requesting directly. so, my issue now is how to manage aliases. 
by the way, this PR fixes authentication

**Comment by dexion** [comment]
@mjalil , `http://username:pass@example.com:9200` didn't work at 6.2.1 with x-pack. In console ot return `200 OK` but app show `0 0` error

**Pull request closed without merging**
